apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OtosanA/Kube.git
    targetRevision: main
    path: workloads/local-path-storage
  destination:
    server: https://172.18.0.3:6443
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
